version: 0.2

#env:
#  variables:
#    key: "value"
#    key: "value"

phases:
  install:
    commands:
      - curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI | jq 'to_entries | [ .[] | select(.key | (contains("Expiration") or contains("RoleArn"))  | not) ] |  map(if .key == "AccessKeyId" then . + {"key":"AWS_ACCESS_KEY_ID"} else . end) | map(if .key == "SecretAccessKey" then . + {"key":"AWS_SECRET_ACCESS_KEY"} else . end) | map(if .key == "Token" then . + {"key":"AWS_SESSION_TOKEN"} else . end) | map("export \(.key)=\(.value)") | .[]' -r > ~/.aws/credentials # work around https://github.com/hashicorp/terraform/issues/8746
      - echo "Prepare terraform file"
      - cd terraform-code
      - echo "terraform { " >> provider-output-backend.tf
      - echo "   backend \"s3\" { " >> provider-output-backend.tf
      - echo "   bucket = \"$target-bucket\"" >> provider-output-backend.tf
      - echo "   key    = \"$state-file\"" >> provider-output-backend.tf
      - echo "   region = \"$region\"" >> provider-output-backend.tf
      - echo "  }" >> provider-output-backend.tf
      - echo "}" >> provider-output-backend.tf
      - cat provider-output-backend.tf
      - terraform init
  build:
    commands:
      - . /tmp/aws_cred_export.txt &&  terraform plan -out testplan && terraform apply testplan
      - echo "Post apply build"
  post_build:
    commands:
      - echo "Nothing to do in the post_build for now"